### ISSUE TITLE
[NCryptEncrypt — 0x80090026]

### ISSUE THREAD

**Issue by amfcdr** [sirAndros/KeePassWinHello#114]
**Describe the bug**

KeePassWinHello is added as a plugin to KeePass, and has been working without an issue for years.

Starting today, whenever pressing the fingerprint reader an exception is thrown:

```
KeePassWinHello.AuthProviderSystemErrorException: NCryptEncrypt
Error code: 0x80090026
at
KeePassWinHello.WinHelloProvider.SECURITY_STATUS.ThrowOnError(S
tring name, Int32 ignoreStatus)
at KeePassWinHello.WinHelloProvider.Encrypt(Bytel] data, Boolean
retry)
at KeePassWinHello.WinHelloProvider.Encrypt(Byte[] data)
at KeePassWinHello.KeyCipher.Protect(ProtectedBinary key)
at KeePassWinHello.ProtectedKey .. ctor(CompositeKey compositeKey,
KeyCipher keyCipher)
at KeePassWinHello.KeyManager.Lock(Boolean isDbLocking, String
dbPath, CompositeKey databaseMasterKey)
at KeePassWinHello.KeyManager.OnDBClosing(Object sender,
FileClosingEventArgs e)
at KeePassWinHello.KeePassWinHelloExt.OnPreFileClosing(Object
sender, FileClosingEventArgs e)
```

**To Reproduce**

1. Open KeePass
2. Wait for the Windows Hello input window
3. Press the fingerprint reader
4. Get the exception message window

**Expected behavior**

The KeePass database should be unlocked and displayed.

**Screenshots**

![KeePassWinHello](https://github.com/user-attachments/assets/06f1bb35-91f2-4d1a-a4ee-5b5251ac8127)
.

## Context

Please complete the following information:

| Component | Version |
|-----------|---------|
| Operating System | Windows 11 Version 23H2 (OS Build 22631.4460) |
| KeePass | Version 2.57.1 (64-bit) |
| Plugin | KeePassWinHello Version 3.3.1 |

**Hardware info**

- HP EliteBook 640 14 inch G11 Notebook PC
- Onboard fingerprint reader
- TPM Manufacturer NTC Version 7.2.3.1 (TPM 2.0)
 
 **Plugin settings**
 
 - [x] Is persistent mode enabled ("Store keys in Windows Credential Manager" checked)
 
 **KeePass settings and environment**
 
 - [ ] Is secure desktop enabled
 - [ ] Is KeePass running under Administrator (in elevated process)
 - [ ] Was it right after hibernation
 - [ ] Was KeePass minified or closed
 

 - ExelconPicker (Version 1.2)
 - Fields Admin Console (Version 0.2)
 - GlobalSearch (Version 1.3.2)
 - KeeAgent (Version 0.13.8)
 - KeeAnywhere (Version 2.1)
 - KeeAutoExec (Version 2.6)
 - KeePassOTP (Version 1.8)
 - KeePassRDP (Version 2.2.2)
 - KeePassVeraCryptMount (Version 1.0.7)
 - KeePassWinHello (Version 3.3.1)
 - KeeTheme (Version 0.10.7)
 - KPScript - Scripting KeePass (Version 2.57.1)
 - Password Counter (Version 0.1)
 - VeraCryptAutoDismount (Version 1.0.3)
 - Yet Another Favicon Downloader (Version 1.2.5)
 
**Additional context**

 - No changes/updates have been done to the KeePass environment/plugins for over three weeks.
 - The computer has been up for over three weeks and KeePass has been always running, so KeePassWinHello hasn't been used for that long.
 - Today, after Windows Update, a mandatory reboot has been done and user login has been achieved through Windows Hello without any issue.
 - After login, KeePass is one of the applications that starts whenever a user logs in, the Windows Hello window popped up and when using the fingerprint reader the exception was thrown.
 - These steps were taken trying to solve the issue:
   1. KeePassWinHello stored keys were cleared, and the plugin was disabled.
   2. KeePass was closed and reopened.
   3. KeePassWinHello was re-enabled and **the exception was immediatelly thrown**.
   4. KeePassWinHello stored keys were cleared, and the plugin was disabled.
   5. KeePass was closed.
   6. Windows Hello fingerprints were deleted and recreated.
   7. Windows was locked and fingerprint reader was used to unlock Windows.
   8. KeePass was reopened.
   9. KeePassWinHello was re-enabled and **the exception was immediatelly thrown**.
   10. KeePass was closed and reopened and **the exception was immediatelly thrown**.
   11. KeePassWinHello stored keys were cleared, and the plugin was disabled.
   12. No further steps were attempted.

**Comment by amfcdr** [comment]
Please disregard this issue.

After an aditional Windows Update, I re-enabled the plugin and it's been working as expected since.

Thank you, for your time and effort.

**Comment by amfcdr** [comment]
KeePassWinHello is working as expected, the issue seemed to be external to the plugin.

Thank you.
