### ISSUE TITLE
RDP session exception

### ISSUE THREAD

**Issue by ollikorhonen405** [sirAndros/KeePassWinHello#66]
When using WSL on other computer over RDP, no Hello is available and it throw exception. Fallback password auth still work.

PS C:\Windows\System32> wsl
XXX:/mnt/c/Windows/System32$ sudo ls

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Invalid window handle.

This API must be called from a thread with a CoreWindow or a window must have been set explicitly.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WindowsHelloAuthenticator.Program.<VerifyUser>d__9.MoveNext() in C:\Users\abctk\Dropbox\develop\rust\wsl_hello_pam\win_components\WindowsHelloAuthenticator\WindowsHelloAuthenticator\Program.cs:line 60
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at WindowsHelloAuthenticator.Program.Main(String[] args) in C:\Users\abctk\Dropbox\develop\rust\wsl_hello_pam\win_components\WindowsHelloAuthenticator\WindowsHelloAuthenticator\Program.cs:line 94
[sudo] password for XXX:

**Comment by sirAndros** [comment]
Hello @ollikorhonen405!
Looks like its an issue of the [WSL-Hello-sudo](https://github.com/nullpo-head/WSL-Hello-sudo) and not of this KeePass plugin.
