### ISSUE TITLE
[NCryptEncrypt - 0x800704C7] ERROR_CANCELLED on db file moving

### ISSUE THREAD

**Issue by sirAndros** [sirAndros/KeePassWinHello#72]
> I have a similar issue. 
> I received the following message which said to post it here. I just moved the Dropbox local storage from my C: drive to a larger E: drive to free up memory from C: The data file was on Dropbox.
> ************** begin error message ***********************
> Something went wrong. Please report the issue in our Github
> repository with the following technical info.
> KeePassWinHello.AuthProviderSystemErrorException:
> NCryptEncrypt
> Error code: S00704C7
> at
> KeePassWinHe11o.WinHe11oProvider.SECURITY_STATUS.CheckSt
> atus(String name, Int32 ignoreStatus)
> at KeePassWinHello.WinHelloProvider.Encrypt(ByteQ data)
> at KeePassWinHello.KeyCipher.Protect(ProtectedBinary key)
> at KeePassWinHello,ProtectedKey..ctor(CompositeKey
> compositeKey, KeyCipher keyCipher)
> at KeePassWinHello.KeyManager.OnDBCIosingfObject
> sender, FileClosingEventArgs e)
> ******************* end error message ***********************
> Here is version information;
> KeePass Version 2.44
> XSL Stylesheets for KDBX XML Installed
> KeePassLibC (1-* File Support) Version 1.38 (DxD1B2)
> 
> I am running on Windows 10 Pro 64 bit Version 1909 OS Build 18363.720
> Installed 11/13/2019
> Hardware: Home made AMD FX-8320 8 Core processor, 32 GB memory

_Originally posted by @rgwebster in https://github.com/sirAndros/KeePassWinHello/issues/42#issuecomment-614845110_

**Comment by sirAndros** [comment]
Fixed in [v3.2](https://github.com/sirAndros/KeePassWinHello/releases/tag/v3.2)
